shuffle:
  javascript:
    - lib/jquery.min.js
    - lib/jquery-ui-1.10.4.min.js
    - helper/js.js
    - helper/sound.js
    - helper/animation.js
    - game/manager.js
    - game/shuffle/manager.js
    - game/shuffle/main.js
  stylesheet: 
    - game/shuffle/main.css
translation:
  javascript:
    - lib/jquery.min.js
    - helper/js.js
    - helper/sound.js
    - helper/animation.js
    - game/manager.js
    - game/translation/manager.js
    - game/translation/main.js
  stylesheet: 
    - game/translation/main.css
irregular:
  javascript:
    - lib/jquery.min.js
    - lib/jquery-ui-1.10.4.min.js
    - helper/js.js
    - helper/action.js
    - helper/sound.js
    - helper/animation.js
    - game/action.js
    - game/manager.js
    - game/irregular/manager.js
    - game/irregular/main.js
  stylesheet: 
    - game/irregular/main.css