play:
  javascript:
    - jquery.min.js
    - tools/animationHelper.js
    - class/gameManager.js
    - play.js
  stylesheet: 
    - play.css
irregular:
  javascript:
    - jquery.min.js
    - irregular.js
  stylesheet: 
    - irregular.css
list:
  javascript:

  stylesheet: 