shuffle:
  javascript:
    - lib/jquery.min.js
    - lib/jquery-ui-1.10.4.min.js
    - helper/extend.js
    - helper/animation.js
    - game/manager.js
    - game/shuffle/manager.js
    - game/shuffle/main.js
  stylesheet: 
    - shuffle.css
translation:
  javascript:
    - lib/jquery.min.js
    - helper/extend.js
    - helper/animation.js
    - game/manager.js
    - game/translation/manager.js
    - game/translation/main.js
  stylesheet: 
    - translation.css
irregular:
  javascript:
    - lib/jquery.min.js
    - lib/jquery-ui-1.10.4.min.js
    - helper/extend.js
    - helper/animation.js
    - game/manager.js
    - game/irregular/manager.js
    - game/irregular/main.js
  stylesheet: 
    - irregular.css