shuffle:
  javascript:
    - jquery.min.js
    - jquery-ui-1.10.4.min.js
    - extend.js
    - tools/animationHelper.js
    - class/gameManager.js
    - class/shuffleManager.js
    - shuffle.js
  stylesheet: 
    - shuffle.css
translation:
  javascript:
    - jquery.min.js
    - extend.js
    - tools/animationHelper.js
    - class/gameManager.js
    - class/translationManager.js
    - translation.js
  stylesheet: 
    - translation.css
irregular:
  javascript:
    - jquery.min.js
    - jquery-ui-1.10.4.min.js
    - extend.js
    - tools/animationHelper.js
    - class/gameManager.js
    - class/irregularManager.js
    - irregular.js
  stylesheet: 
    - irregular.css