index:
  javascript:
    - lib/jquery.min.js
    - model/action.js
    - helper/js.js
    - helper/action.js
    - login/action.js
    - login/manager.js
    - login/main.js
  stylesheet:
    - login/main.css