index:
  javascript:
    - lib/jquery.min.js
    - helper/js.js
    - helper/animation.js
    - helper/action.js
    - model/action.js
    - home/manager.js
    - home/main.js
  stylesheet:
    - home/main.css