gameResult:
  url: game/result
  module: game
  action: result
gamePlay:
  url: game/:type
  module: game
  action: play
  layout: default
loginUser:
  url: login/connect
  module: login
  action: connect
  layout: default
login:
  url: login
  module: login
  action: index
  layout: default
default:
  module: home
  action: index
  layout: default