gameResult:
  url: game/result
  module: game
  action: result
gamePlay:
  url: game/play
  module: game
  action: play
  layout: default
gameIrregular:
  url: game/irregular
  module: game
  action: irregular
  layout: default
gameList:
  url: game/list
  module: game
  action: getList
loginUser:
  url: login/user
  module: login
  action: logUser
  layout: default
login:
  url: login
  module: login
  action: index
  layout: default
default:
  module: home
  action: index
  layout: default