gameResult:
  url: game/result
  module: game
  action: result
gamePlay:
  url: game/translation
  module: game
  action: translation
  layout: default
gameIrregular:
  url: game/irregular
  module: game
  action: irregular
  layout: default
loginUser:
  url: login/user
  module: login
  action: logUser
  layout: default
login:
  url: login
  module: login
  action: index
  layout: default
default:
  module: home
  action: index
  layout: default